Aleksandr_Voschilo_Homework_26 done
eugene-okulik/QAP-09onl pull request #117
Opened 2022-11-02 18:46 UTC by writeln2012

2022-11-04 11:06 UTC, eugene-okulik approved these changes
Хардкод id - плохая идея. Подходит только в том случае, если ты уверен в том, что сущность с таким id будет жить вечно.

2022-11-04 11:06 UTC, eugene-okulik commented on homework/Aleksandr_Voschilo/Homework_26/hw_26.py
> +        "id": 2,
Все было бы хорошо, но вот кто-то взял и добавил в систему мем с id 2 и теперь этот тест и тест удаления не работают, т.к. мем с id 2 - не твой )).
Для тестов, которые расчитывают на то, что в системе уже есть то, что они пытаются создать или удалить, нужно вначале теста делать шаги, которые создают ту сущность, с которой будет идти работа в этом тесте.

2022-11-04 11:06 UTC, eugene-okulik requested changes
Случайно нажал апрув. исправляюсь

2022-11-04 11:15 UTC, eugene-okulik commented on homework/Aleksandr_Voschilo/Homework_26/hw_26.py
> +        "id": 2,
мемас прикольный :+1:

2022-11-05 08:03 UTC, writeln2012 commented on homework/Aleksandr_Voschilo/Homework_26/hw_26.py
> +        "id": 2,
Исправил

2022-11-05 08:03 UTC, writeln2012 commented
Исправил

2022-11-07 05:12 UTC, eugene-okulik commented
> Исправил

С фикстурой создания прям круто смотрится

2022-11-07 05:12 UTC, eugene-okulik approved these changes

2022-11-07 05:12 UTC, merged

2022-11-07 05:39 UTC, eugene-okulik commented
Сейчас посмотрел как ты получаешь и хранишь токен. Все работает хорошо и правильно. Но у тебя для этого 2 фикстуры (token и login), хотя могла быть одна (login). В фикстуре login вместо просто `return` можно было сделать `return token`, а в конце можно сделать `return response_login['token']`. Тогда фикстура token вообще не нужна.  
И кстати в конце фикстуры login ты записываешь результат в файл и не пользуешься менеджером контекста. И еще бы ничего, если бы ты закрывал файл, но не закрываешь.

2022-11-08 07:49 UTC, writeln2012 commented
большое спасибо, все осознал