Vajda Maksim: Homework 26 completed
eugene-okulik/QAP-09onl pull request #118
Opened 2022-11-02 19:43 UTC by metalveor

2022-11-04 11:39 UTC, eugene-okulik requested changes
В тестах ты захардкодил id и теперь тесты не работают, т.к. этот id уже занят чужим мемом.  Если в тестах тебе нужна какая-то сущность с которой нужно производить какие-то действия, то в начале этого теста нужно создать такую сущность. Исключение может быть только в ситуации, если ты уверен в том, что сущность с таким айди будет жить вечно.

2022-11-05 11:37 UTC, metalveor commented
Removed hardcoding. 
Fixed Homework_26.py

2022-11-07 05:17 UTC, eugene-okulik commented on homework/vajda_maksim/homework_26/test_homework_26.py
>      assert response['url'] == "https://s00.yaplakal.com/pics/pics_original/4/6/0/7027064.jpg"
На занятии еще обсудили, что неплохо бы удалять тот мем, который был создан для теста. Можно это сделать в конце теста или в фикстуре создания мема после `yield`

2022-11-07 05:17 UTC, eugene-okulik approved these changes

2022-11-07 05:18 UTC, merged

2022-11-07 05:41 UTC, eugene-okulik commented
Сейчас посмотрел как ты получаешь и хранишь токен. Все работает хорошо и правильно. Но у тебя для этого 2 фикстуры (token и authorize), хотя могла быть одна (authorize). В фикстуре authorize вместо просто `return` можно было сделать `return token`, а в конце можно сделать `return response["token"]`. Тогда фикстура token вообще не нужна.