Denis Fadeev: 23 Homework is incomplete
eugene-okulik/QAP-09onl pull request #120
Opened 2022-11-03 13:16 UTC by xSmugxJoex

23 homework is incomplete, an error pops up on the page with test bes…t_sales.py

2022-11-04 10:23 UTC, eugene-okulik requested changes

2022-11-04 10:23 UTC, eugene-okulik commented on homework/Denis_Fadeev/homework_23/conftest.py
> +    service = Service(executable_path='C:\\TMS\\chromedriver.exe')
Добавь `chromedriver.exe` в папку, находящуюся в PATH

2022-11-04 10:23 UTC, eugene-okulik commented on homework/Denis_Fadeev/homework_23/pages/best_sales.py
> +clothes_by_in_stock = (By.ID, 'selectProductSoft', 'In stock')
Падает от того, что у тебя здесь 3 параметра вместо двух: `By.ID`,` 'selectProductSoft'`, `'In stock'`

2022-11-07 12:56 UTC, xSmugxJoex commented on homework/Denis_Fadeev/homework_23/conftest.py
> +    service = Service(executable_path='C:\\TMS\\chromedriver.exe')
Done.

2022-11-07 12:56 UTC, xSmugxJoex commented on homework/Denis_Fadeev/homework_23/pages/best_sales.py
> +clothes_by_in_stock = (By.ID, 'selectProductSoft', 'In stock')
Fixed.

2022-11-13 07:29 UTC, eugene-okulik approved these changes

2022-11-13 07:29 UTC, merged