Pavel Malashko: homework_26 completed
eugene-okulik/QAP-09onl pull request #121
Opened 2022-11-03 21:05 UTC by Malashko17

Added files with API tests.

2022-11-04 11:42 UTC, eugene-okulik requested changes
В тестах ты захардкодил id и теперь тесты не работают, т.к. этот id уже занят чужим мемом. Если в тестах тебе нужна какая-то сущность с которой нужно производить какие-то действия, то в начале этого теста нужно создать такую сущность. Исключение может быть только в ситуации, если ты уверен в том, что сущность с таким айди будет жить вечно.

2022-11-07 17:29 UTC, Malashko17 commented
Исправил, сейчас вроде тесты работают как нужно - независимо друг от друга

2022-11-13 07:47 UTC, eugene-okulik requested changes

2022-11-13 07:47 UTC, eugene-okulik commented on homework/Pavel_Malashko/Homework_26/test_requests.py
> +                assert tag == 'fun', 'meme with "fun" tag is not found'
Этот тест возвращает ложно позитивный результат. Если сделать:
```
            if tag == 'laskjdhfalskdj':
                assert tag == 'fualskdjfasldkn', 'meme with "fun" tag is not found'
```
тест будет Passed, хоть такого тэга и нет

2022-11-13 09:03 UTC, Malashko17 commented on homework/Pavel_Malashko/Homework_26/test_requests.py
> +                assert tag == 'fun', 'meme with "fun" tag is not found'
Исправил, оказывается не правильно понимал принцип работы ассерта

2022-11-13 09:49 UTC, eugene-okulik approved these changes

2022-11-13 09:50 UTC, merged