Dmitry Shulga: Homework 26 completed
eugene-okulik/QAP-09onl pull request #127
Opened 2022-11-05 08:39 UTC by ShulgaDmitry

2022-11-07 05:53 UTC, eugene-okulik requested changes
Подсказка: авторизацию нужно вынести в фикстуру

2022-11-07 05:53 UTC, eugene-okulik commented on homework/dmitry_shulga/homework_26/test_homework_26.py
> +def test_get_token(base_url):
Получение токена - это не тест. Он должен отрабатывать независимо от тестов. Если запустить выполнение одного теста, когда сохраненный токен нерабочий, все падает:
```
pytest -v test_homework_26.py::test_get_all_posts
```

2022-11-07 05:53 UTC, eugene-okulik commented on homework/dmitry_shulga/homework_26/conftest.py
> +        'Authorization': 'Bk4wHEq1E3cIgPp'
А здесь захардкодил авторизацию

2022-11-07 13:37 UTC, ShulgaDmitry commented
Вынес авторазицию в фикстуру

2022-11-13 07:56 UTC, eugene-okulik commented on homework/dmitry_shulga/homework_26/test_homework_26.py
> +    requests.request('DELETE', f'{base_url}/meme/{put_id}', headers=headers)
Как говорили на занятии, удаление можно сделать здесь, а можно в фикстуре. И тот и тот варианты хороши, но имеют разные последствия. Если удаление реализовано в фикстуре, то пост удалится независимо от того упал тест или нет. А когда удаление реализовано здесь, то пост не удалится если тест упадет. И нужно осознанно подходить к выбору где это релизовать. При удалении в фикстуре, система всегда будет оставаться чистой после выполнения тестов, а если удалять в тесте, то остается тот мем, на котором тест упал и это дает возможность проанализировать что пошло не так с этим мемом.

2022-11-13 07:56 UTC, eugene-okulik approved these changes

2022-11-13 07:56 UTC, merged