Sveta_Rumyantseva: Homework_26 is completed
eugene-okulik/QAP-09onl pull request #142
Opened 2022-11-10 21:05 UTC by Svetlana-Rumyantseva

2022-11-13 10:12 UTC, eugene-okulik requested changes

2022-11-13 10:12 UTC, eugene-okulik commented on homework/Sveta_Rumyantseva/Homework_26/test_requests.py
> +                        assert val == 'fun'
Этот тест вернет ложно позитивный результат. Если заменить
```
                    if val == 'fun':
                        assert val == 'fun'
```
на
```
                    if val == 'sdfgsdfgsdfgweergwer':
                        assert val == 'wersdfsdfsdfgwergewrgwerg'
```
и запустить тест, он вернет Passed

2022-11-18 14:43 UTC, Svetlana-Rumyantseva commented on homework/Sveta_Rumyantseva/Homework_26/test_requests.py
> +                        assert val == 'fun'
Действительно. Исправила. Спасибо за подсказку.

2022-11-27 07:13 UTC, eugene-okulik approved these changes

2022-11-27 07:13 UTC, merged