Tanya Shevchuk: homework_26
eugene-okulik/QAP-09onl pull request #149
Opened 2022-11-16 13:36 UTC by TatyanaShevchuk

не получается 4 задание, буду разбираться

2022-11-21 11:45 UTC, eugene-okulik requested changes
Все ок, четвертое жду.
Как вариант - собрать все теги всех мемов в один список, а потом, проверить есть ли нужный тег в этом списке

2022-11-21 11:45 UTC, eugene-okulik commented on homework/tanya_shevchuk/homework_26/conftest.py
> +def test_create_meme(base_url, user_authorization):
Лучше не называть его чем-то начинающимся на test_

2022-11-22 11:08 UTC, TatyanaShevchuk commented on homework/tanya_shevchuk/homework_26/conftest.py
> +def test_create_meme(base_url, user_authorization):
исправила название, добавила 4 задание

2022-11-26 06:25 UTC, eugene-okulik approved these changes

2022-11-26 06:25 UTC, merged