Dudin Andrei: Homework 26
eugene-okulik/QAP-09onl pull request #151
Opened 2022-11-16 19:12 UTC by AndreiDudin

2022-11-21 11:50 UTC, eugene-okulik requested changes

2022-11-21 11:50 UTC, eugene-okulik commented on homework/andrey_dudin/homework_26/tests_api.py
> +                        assert name == 'fun'
Здесь у тебя ложно позитивный результат. Попробуй заменить ожидаемый тег на 'kdjfhiurhfkjsdhfksjhfuwhfkjsdhfsduywgejh' и запусти тест - он будет `Passed`, хотя такого тега нет.

2022-11-21 21:19 UTC, AndreiDudin commented on homework/andrey_dudin/homework_26/tests_api.py
> +                        assert name == 'fun'
Поправил в коммите Dudin Andrei: Homework 26 with fix

2022-11-22 07:15 UTC, eugene-okulik approved these changes

2022-11-22 07:15 UTC, merged