Vitali_Zalutski_homework21 done
eugene-okulik/QAP-09onl pull request #56
Opened 2022-10-16 10:20 UTC by Vitalik2997

2022-10-20 05:56 UTC, eugene-okulik requested changes
Сейчас не хватает:
1. Действия, которое отрабатывает до и после каждого теста.
2. Раз уж ты используешь selenium, то нужно добавить `chromedriver` в путь, находящийся в `Path`, чтобы не приходилось делать это: `service = Service(executable_path='C:\\chromedriver.exe')`
3. Тестов меньше десяти

2022-10-20 05:56 UTC, eugene-okulik commented on homework/Vitali_Zalutski/Home_Work_21/test_Vitali_Zalutski_hw21.py
> +def test_go_to_site(driver):
Задание было сделать простые тесты, которые по сути ничего не тестируют. Главная задача - научиться работать с фикстурами с помощью простых бессмысленных тестиков. Этот тест уже посложнее. И более того, ничего не проверяет

2022-10-20 05:56 UTC, eugene-okulik commented on homework/Vitali_Zalutski/Home_Work_21/test_Vitali_Zalutski_hw21.py
> +    print('Before Testing "test_simple_1"')
Для того, чтобы перед каждым тестом и после каждого теста печатался какой-то текст, нужно сделать фикстуру с `scope='function'`

2022-10-20 05:56 UTC, eugene-okulik commented on homework/Vitali_Zalutski/Home_Work_21/pytest.ini
> +    ignore::UserWarning
Здесь можно было не отключить ворнинги, а прописать simple и hard как ожидаемые

2022-10-20 16:05 UTC, Vitalik2997 commented
доделал

2022-10-24 06:51 UTC, eugene-okulik approved these changes

2022-10-24 06:51 UTC, merged