Sveta_Rumyantseva: Homework_22 completed
eugene-okulik/QAP-09onl pull request #89
Opened 2022-10-25 12:24 UTC by Svetlana-Rumyantseva

2022-10-28 07:37 UTC, eugene-okulik requested changes

2022-10-28 07:37 UTC, eugene-okulik commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    ActionChains(driver).click(add_button).perform()  # or  add_button.click()
В качестве практики экшенчейнов хорошо, но (на будущее) лучше использовать то, что проще - то что у тебя в коментарии

2022-10-28 07:37 UTC, eugene-okulik commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    sleep(2)  # demonstration
Слипы с целью демонстрации - это моя фишка. Потому что я демонстрирую. А тебе в коменте нужно написать почему ты используешь здесь слип, а не `WebDriverWait`. А, возможно, ни слип ни ожидания не нужны.

2022-11-01 21:31 UTC, Svetlana-Rumyantseva commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    sleep(2)  # demonstration
Согласна здесь они лишние оба. 
А вообще я имела ввиду для демонстрации: поставить небольшую задержку, чтобы успеть заметить результат в браузере (первый слип вообще бессмысленный, при втором слипе видно как нажимается кнопочка))).

2022-11-01 21:31 UTC, Svetlana-Rumyantseva commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    ActionChains(driver).click(add_button).perform()  # or  add_button.click()
Поняла.)) забыла удалить коммент, просто я пробывала для себя и так, и так.

2022-11-01 21:48 UTC, Svetlana-Rumyantseva commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    sleep(2)  # demonstration
проверила без второго слипа, тест вообще падает. Возможно, второй слип нужен, чтобы успел отработать ActionChains?!? А если честно, здесь не могу четко аргументировать "почему ты используешь здесь слип, а не WebDriverWait"

2022-11-04 09:53 UTC, eugene-okulik commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    sleep(2)  # demonstration
Перефразирую вопрос. Почему ты не использовала` WebDriverWait(driver, 10).until(EC.presence_of_element_located.....`, а вместо него использовала `sleep`?

2022-11-04 22:16 UTC, Svetlana-Rumyantseva commented on homework/Sveta_Rumyantseva/Homework_22/test_task_for_hw22.py
> +    sleep(2)  # demonstration
Теперь разобралась. Все исправила. Спасибо за разъяснения) Действительно, нашла в инете, что time.sleep - bad practice.

2022-11-06 11:40 UTC, eugene-okulik approved these changes

2022-11-06 11:40 UTC, merged