Amelchenko dima hw 22
eugene-okulik/QAP-09onl pull request #90
Opened 2022-10-25 12:33 UTC by AmelchenkoDima

2022-10-28 08:13 UTC, eugene-okulik requested changes

2022-10-28 08:13 UTC, eugene-okulik commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +def task1(driver):
Ты сделал все как функции, а нужно как тесты.

2022-10-28 08:13 UTC, eugene-okulik commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +    driver.implicitly_wait(10)
В функции driver() ты уже включил implicitly_wait для драйвера. Если его один раз включаешь, он работает пока не завершится работа программы. Т.е. в самом начале включаешь его - и не думаешь о нем

2022-10-28 08:13 UTC, eugene-okulik commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +    driver.quit()
Это закрывает браузер и следующая функция не может стартовать.

2022-10-28 13:08 UTC, AmelchenkoDima commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +    driver.quit()
Я и реализовал это как  три разных теста для которых открывается браузер заново

2022-10-29 15:50 UTC, AmelchenkoDima commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +    driver.implicitly_wait(10)
Исправил

2022-10-29 15:50 UTC, AmelchenkoDima commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +def task1(driver):
Исправил

2022-10-31 06:56 UTC, eugene-okulik commented on homework/Amelchenko_Dima/hw_22/hw_22.py
> +#
Закомментированные строки в готовом коде лучше убирать

2022-10-31 06:56 UTC, eugene-okulik approved these changes

2022-10-31 06:56 UTC, merged